### ISSUE TITLE
Starting project locally with Docker

### ISSUE THREAD

**Issue by geowatson** [dailydotdev/daily-gateway#41]
Hello, could you please provide docker-compose.yml file or README doc on how to start daily-gateway locally (with docker)? Thank you.

**Comment by geowatson** [comment]
<img width="733" alt="Screen Shot 2020-09-05 at 4 42 25 PM" src="https://user-images.githubusercontent.com/29640561/92306313-ca83f580-ef96-11ea-9667-55133906a14f.png">
Getting this error while running `yarn start`

**Comment by idoshamun** [comment]
Hey!
Sorry for the late reply, I didn't notice you submitted an issue here.
In order to run locally the project without building it, please run `yarn watch`.
If you want, you can use docker-compose as well. You can find the instructions here:
https://github.com/dailydotdev/daily#-running-dailydev-locally
